# command to run tests
language: python

python:
    - 3.5

install:
    - pip install .
    - pip install -r requirements.txt -r test-requirements.txt

script:
    - coverage run --source=futhon_test setup.py test

after_success:
    - coveralls